### ISSUE TITLE
Feature request: Add translation ability to Whisper-diarization Google Colab

### ISSUE THREAD

**Issue by BlohoJo** [Transcripts4All/tools4all#5]
Is it possible to add the ability the translate audio files to [Whisper-diarization Google Colab](https://github.com/Transcripts4All/tools4all/issues/4)? For example, load a Russian language audio file and translate it into English while identifying the speakers?

**Comment by ScriptTiger** [comment]
It's not possible at this time, since there are several core components which depend on everything being the same language. Not allowing translation is an intentional design decision.

Refer to the following issue for more details:
https://github.com/MahmoudAshraf97/whisper-diarization/issues/146
